### ISSUE TITLE
Queue inference for numba_dpex kernel args returns incorrect values

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#1021]
The following code should raise a `ComputeFollowsDataInferenceError`, however such an exception is not raised:

```python
import dpnp
import dpctl

import numba_dpex as dpex
from numba_dpex.core.exceptions import ComputeFollowsDataInferenceError


@dpex.kernel
def sum_kernel(a, b, c):
    i = dpex.get_global_id(0)
    c[i] = a[i] + b[i]

q1 = dpctl.SyclQueue()
q2 = dpctl.SyclQueue()

print(q1 == q2)
a = dpnp.ones(1, sycl_queue=q1)
b = dpnp.ones(1, sycl_queue=q2)
c = dpnp.empty_like(a)

sum_kernel[dpex.Range(1)](a, b, c)
```
Inside dispatcher when the type of the input arguments is inferred I see that all the args are inferred as `usm_ndarray` type with the same queue.

**Comment by diptorupd** [comment]
The problem is that the `self.typingctx.resolve_argument_type` is inferring the type of all three args `a`, `b`, and `c` as the same. The issue does not crop up if I change the `usm_type` attribute of `b`. Seems like some sort of caching is to blame.

**Comment by diptorupd** [comment]
> Seems like some sort of caching is to blame.

Remembered it a second after hitting enter. The typing context caches the type post resolution. For `DpnpNdArray` and `USMNdArray` the key for caching is based on:

https://github.com/IntelPython/numba-dpex/blob/000d5cd3aaf0f57db31c4142be0b5333fa0eb95a/numba_dpex/core/types/usm_ndarray_type.py#L194

Therefore, the argtype is resolved the same for all three arguments as they all use the same default device.

**Comment by diptorupd** [comment]
Got fixed when the `key` for the `USMNdArray` type was updated to include the `queue`. The reproducer now raises an `ExecutionQueueInferenceError` with following traceback:

```bash
Traceback (most recent call last):
  File "/localdisk/work/diptorup/devel/numba-dpex/driver.py", line 23, in <module>
    sum_kernel[dpex.Range(1)](a, b, c)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/core/kernel_interface/dispatcher.py", line 412, in __call__
    ty_queue = determine_kernel_launch_queue(
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/core/kernel_interface/utils.py", line 72, in determine_kernel_launch_queue
    raise ExecutionQueueInferenceError(
numba_dpex.core.exceptions.ExecutionQueueInferenceError: Execution queue for kernel "sum_kernel" could be deduced using compute follows data programming model. The usm_ndarray arguments 0,1,2 were not allocated on the same queue.
```
