### ISSUE TITLE
Make the new dispatcher work with Numba `new_style` errors.

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#1195]
The numba_dpex.experimental.dispatcher.KernelDispacther does not work when the NUMBA_CAPTURED_ERROR is set to new_style.

Reproducer:

```python
import dpctl
import dpnp
from numba.core import config
import numba_dpex.experimental as exp_dpex
from numba_dpex import Range


@exp_dpex.kernel(
    release_gil=False,
    no_compile=True,
    no_cpython_wrapper=True,
    no_cfunc_wrapper=True,
)
def add(a, b, c):
    c[0] = b[0] + a[0]


q = dpctl.SyclQueue()
a = dpnp.ones(100, sycl_queue=q)
b = dpnp.ones_like(a, sycl_queue=q)
c = dpnp.zeros_like(a, sycl_queue=q)
r = Range(100)


current_captured_error_style = config.CAPTURED_ERRORS
config.CAPTURED_ERRORS = "new_style"

try:
    exp_dpex.call_kernel(add, r, a, b, c)
    assert c[0] == b[0] + a[0]
except Exception as e:
    print("Unexpected error when calling kernel" + str(e))

config.CAPTURED_ERRORS = current_captured_error_style

```

**Comment by diptorupd** [comment]
```bash
Traceback (most recent call last):
  File "/localdisk/work/diptorup/devel/numba-dpex/driver.py", line 29, in <module>
    exp_dpex.call_kernel(add, r, a, b, c)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 762, in compile_extra
    return pipeline.compile_extra(func)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 460, in compile_extra
    return self._compile_bytecode()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 528, in _compile_bytecode
    return self._compile_core()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 503, in _compile_core
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 494, in _compile_core
    pm.run(self.state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 88, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1078, in propagate
    errors = self.constraints.propagate(self)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 177, in propagate
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 155, in propagate
    constraint(typeinfer)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 578, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 601, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1557, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/context.py", line 196, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 312, in get_call_type
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 308, in get_call_type
    sig = temp.apply(nolitargs, nolitkws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 351, in apply
    sig = generic(args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 614, in generic
    disp, new_args = self._get_impl(args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 713, in _get_impl
    impl, args = self._build_impl(cache_key, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 817, in _build_impl
    disp_type.get_call_type(self.context, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 541, in get_call_type
    self.dispatcher.get_call_template(args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 363, in get_call_template
    self.compile(tuple(args))
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 762, in compile_extra
    return pipeline.compile_extra(func)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 460, in compile_extra
    return self._compile_bytecode()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 528, in _compile_bytecode
    return self._compile_core()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 503, in _compile_core
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 494, in _compile_core
    pm.run(self.state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 88, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1078, in propagate
    errors = self.constraints.propagate(self)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 177, in propagate
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 155, in propagate
    constraint(typeinfer)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 578, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 601, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1557, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/context.py", line 196, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 312, in get_call_type
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 308, in get_call_type
    sig = temp.apply(nolitargs, nolitkws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 351, in apply
    sig = generic(args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 965, in generic
    result = self._definition_func(self.context, *args, **kws)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/experimental/launcher.py", line 311, in intrin_launch_trampoline
    kmodule: _KernelModule = kernel_fn.dispatcher.compile(kernel_sig)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/experimental/kernel_dispatcher.py", line 306, in compile
    kcres: _KernelCompileResult = self._compiler.compile(
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/experimental/kernel_dispatcher.py", line 99, in compile
    kcres = self._compile_cached(args, return_type)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/experimental/kernel_dispatcher.py", line 145, in _compile_cached
    kernel_cres: CompileResult = self._compile_core(args, return_type)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 762, in compile_extra
    return pipeline.compile_extra(func)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 460, in compile_extra
    return self._compile_bytecode()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 528, in _compile_bytecode
    return self._compile_core()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 503, in _compile_core
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 494, in _compile_core
    pm.run(self.state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 88, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1078, in propagate
    errors = self.constraints.propagate(self)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 177, in propagate
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 155, in propagate
    constraint(typeinfer)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 481, in __call__
    self.fallback(typeinfer)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 704, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 601, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1557, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/context.py", line 196, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/context.py", line 248, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 312, in get_call_type
    raise e
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/types/functions.py", line 308, in get_call_type
    sig = temp.apply(nolitargs, nolitkws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 351, in apply
    sig = generic(args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 614, in generic
    disp, new_args = self._get_impl(args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 713, in _get_impl
    impl, args = self._build_impl(cache_key, args, kws)
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 774, in _build_impl
    jitter = self._get_jit_decorator()
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typing/templates.py", line 742, in _get_jit_decorator
    jitter = jit_registry[target_hw]
  File "/nfs/site/home/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/registry.py", line 100, in __getitem__
    return super(DelayedRegistry, self).__getitem__(item)
KeyError: <class 'numba_dpex.core.targets.kernel_target.SyclDevice'>

```
