### ISSUE TITLE
mod ufuncs does not work for dpnp

### ISSUE THREAD

**Issue by ZzEeKkAa** [IntelPython/numba-dpex#1296]
# Reproduction

1. Add these lines to the end at `numba_dpex/tests/dpjit_tests/parfors/test_dpnp_ufuncs.py`:

```python
if __name__ == "__main__":
    test_binary_ops("mod",dpnp.int64)
```

2. Comment out `cbrt` from `_unsupported` at `numba_dpex/core/typing/dpnpdecl.py`
3. Run
```shell
ONEAPI_DEVICE_SELECTOR=opencl:cpu python -m numba_dpex.tests.dpjit_tests.parfors.test_dpnp_ufuncs
```

4. Output:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/yevhenii/Projects/numba-dpex/numba_dpex/tests/dpjit_tests/parfors/test_dpnp_ufuncs.py", line 190, in <module>
    test_unary_ops("mod",dpnp.int64)
  File "/home/yevhenii/Projects/numba-dpex/numba_dpex/tests/dpjit_tests/parfors/test_dpnp_ufuncs.py", line 171, in test_unary_ops
    actual = f(a)
             ^^^^
  File "/home/yevhenii/Projects/numba/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/yevhenii/Projects/numba/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in dpex_dpjit_nopython mode pipeline (step: nopython frontend)
Untyped global name 'uop': Cannot determine Numba type of <class 'function'>

File "numba_dpex/tests/dpjit_tests/parfors/test_dpnp_ufuncs.py", line 169:
    def f(a):
        return uop(a)
        ^
```

# Numba version
Equivalent code for numba+numpy works okay:

```python
    import numba
    import numpy as np

    @numba.njit
    def func(a, b):
        return np.mod(a, b)
    
    a = np.ones(10, dtype=np.int64)
    b = np.ones(10, dtype=np.int64)

    print(func(a,b))
```

**Comment by ZzEeKkAa** [comment]
After playing around with it, it appears that this function implementation was excluded by set of `_aliases`. I've tried to remove it from there and it looks like nothing serious got broken. Keeping it as a workaround.
