### ISSUE TITLE
Can't determine Numba type of get_global_id when it's imported

### ISSUE THREAD

**Issue by chudur-budur** [IntelPython/numba-dpex#1311]
```python
import dpnp
from numba_dpex import Range, get_global_id
import numba_dpex.experimental as ndpx_ex


@ndpx_ex.kernel
def foo(a):
    i = get_global_id(0)
    a[i] = 0


a = dpnp.ones(10, dtype=dpnp.int64)
print(a)

ndpx_ex.call_kernel(foo, Range(*a.shape), a)

print(a)
```

Gives this error:

```bash
[1 1 1 1 1 1 1 1 1 1]
Traceback (most recent call last):
  File "/localdisk/work/$USER/numba-dpex/my-driver.py", line 690, in <module>
    ndpx_ex.call_kernel(foo, Range(*a.shape), a)
  File "/localdisk/work/$USER/numba-dpex/numba_dpex/experimental/launcher.py", line 200, in call_kernel
    _call_kernel(kernel_fn, index_space, *kernel_args)
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in dpex_dpjit_nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<intrinsic _submit_kernel_sync>) found for signature:

 >>> _submit_kernel_sync(type(KernelDispatcher(<function foo at 0x7f359bba3e20>)), Range<1>, UniTuple(DpnpNdArray(dtype=int64, ndim=1, layout=C, address_space=1, usm_type=device, device=level_zero:gpu:0, sycl_queue=DpctlSyclQueue on level_zero:gpu:0) x 1))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Intrinsic in function '_submit_kernel_sync': File: ../../../../../../../numba-dpex/numba_dpex/experimental/launcher.py: Line 72.
    With argument(s): '(type(KernelDispatcher(<function foo at 0x7f359bba3e20>)), Range<1>, UniTuple(DpnpNdArray(dtype=int64, ndim=1, layout=C, address_space=1, usm_type=device, device=level_zero:gpu:0, sycl_queue=DpctlSyclQueue on level_zero:gpu:0) x 1))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in dpex_kernel_nopython mode pipeline (step: nopython frontend)
   Untyped global name 'get_global_id': Cannot determine Numba type of <class 'function'>

   File "my-driver.py", line 683:
   def foo(a):
       i = get_global_id(0)
       ^

  raised from /localdisk/work/$USER/opt/miniconda3/envs/ndpx/lib/python3.10/site-packages/numba/core/typeinfer.py:1482

During: resolving callee type: Function(<intrinsic _submit_kernel_sync>)
During: typing of call at /localdisk/work/$USER/numba-dpex/numba_dpex/experimental/launcher.py (219)


File "numba_dpex/experimental/launcher.py", line 219:
def _call_kernel(kernel_fn, index_space, *kernel_args) -> None:
    <source elided>
    # print(f"type(kernel_fn) = {type(kernel_fn)}")
    _submit_kernel_sync(  # pylint: disable=E1120

```

But it works when we use `get_global_id()` directly from the `numba_dpex` namespace:

```python
import dpnp
import numba_dpex
from numba_dpex import Range, get_global_id
import numba_dpex.experimental as ndpx_ex


@ndpx_ex.kernel
def foo(a):
    i = numba_dpex.get_global_id(0)
    a[i] = 0


a = dpnp.ones(10, dtype=dpnp.int64)
print(a)

ndpx_ex.call_kernel(foo, Range(*a.shape), a)

print(a)
```

output:

```bash
[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
```

**Comment by ZzEeKkAa** [comment]
I've experienced similar issue, but it is irrelevant since we are using `item` and `nd_item` now.

**Comment by diptorupd** [comment]
It is a known issue for a long time https://github.com/IntelPython/numba-dpex/issues/693. The only solution would have been to add all the functions to `globals`. Look at https://github.com/IntelPython/numba-dpex/compare/main...spokhode/fix/693 for my proposed fix.

But, as @ZzEeKkAa it is no longer applicable as we will switch to the `kernel_api` classes.
