### ISSUE TITLE
`ValueError: underlying buffer has been detached` when locale is `en_US`

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#321]
Reproducer:
```
export LANG=en_US
python setup.py develop
```
Ouptut:
```
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    setup(**metadata)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 85, in run
    spirv_compile()
  File "setup.py", line 128, in spirv_compile
    subprocess.check_call(clang_args, stderr=subprocess.STDOUT, shell=False)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/subprocess.py", line 753, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-dev/lib/python3.7/subprocess.py", line 1398, in _get_handles
    errwrite = sys.__stdout__.fileno()
ValueError: underlying buffer has been detached
```
Quick fix:
```
export LANG=en_US.UTF-8
```

**Comment by diptorupd** [comment]
Does not happen for me anymore.
