### ISSUE TITLE
Unexplained error messages when not all required packages installed

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#66]
As a developer I have installed numba-dppy: `python setup.py develop`. It works without errors.
When I start tests `python -m unuttest numba_dppy.tests -v` I see strange fails:
```
======================================================================
ERROR: test_arg_with_accessor (numba_dppy.tests.test_arg_accessor.TestDPPYArgAccessorGPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\tests\test_arg_accessor.py", line 58, in test_arg_with_accessor
    A, B, C, sum_with_accessor)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\tests\test_arg_accessor.py", line 23, in call_kernel
    func[global_size, dppy.DEFAULT_LOCAL_SIZE](A, B, C)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\compiler.py", line 511, in __call__
    kernel = self.specialize(*args)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\compiler.py", line 534, in specialize
    self.access_types)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\compiler.py", line 137, in compile_kernel
    ordered_arg_access_types=access_types)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\compiler.py", line 356, in __init__
    self.spirv_bc = spirv_generator.llvm_to_spirv(self.context, self.binary)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\spirv_generator.py", line 174, in llvm_to_spirv
    return mod.finalize()
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\spirv_generator.py", line 126, in finalize
    self._cmd.generate(ipath=self._llvmfile, opath=spirv_path)
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\spirv_generator.py", line 63, in generate
    check_call(["opt","-O1","-o",ipath+'.bc',ipath])
  File "C:\Users\spokhode\dev\numba-dppy\numba_dppy\spirv_generator.py", line 24, in check_call
    return _real_check_call(*args, **kwargs)
  File "c:\Miniconda3\envs\spokhode-numba-dppy-dev\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\Miniconda3\envs\spokhode-numba-dppy-dev\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\Miniconda3\envs\spokhode-numba-dppy-dev\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\Miniconda3\envs\spokhode-numba-dppy-dev\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

As an experienced user I know that it is because not all packages are installed. Then I go to see README with list of packages I need to install: llvm-spirv, llvmdev, spirv-tools.

But I do not know how new developers will understand the root cause of the problem.

**Comment by diptorupd** [comment]
The development environment setup for numba-dpex has improved significantly since this issue was opened. We now offer better README and getting started guides, environment.yml files, docker and improved build system setup.
Moreover all requirements are now fulfill-able via wheels and conda packages.

Specific to the posted error back trace, the issue can still occur but user will be prompted that `dpcpp-llvm-spirv` package is missing.
