### ISSUE TITLE
Example usm_ndarray.py is failing

### ISSUE THREAD

**Issue by mingjie-intel** [IntelPython/numba-dpex#838]
Example case usm_ndarray.py is failing with following error:

```
N 10
Using device ...
    Name            Intel(R) UHD Graphics [0x9bca]
    Driver version  1.3.24278
    Vendor          Intel(R) Corporation
    Filter string   level_zero:gpu:0

A :  <dpctl.tensor._usmarray.usm_ndarray object at 0x7f3a13a92200>
B :  <dpctl.tensor._usmarray.usm_ndarray object at 0x7f3a13a92190>
/localdisk/work/mingjie2/sandbox/numba_dpex_825/numba-dpex/numba_dpex/compiler.py:775: UserWarning: Compute will follow data! Please do not use context manager to specify a SYCL queue to submit the kernel. The queue will be selected from the data.
  warnings.warn(cfd_ctx_mgr_wrng_msg)
Traceback (most recent call last):
  File "/localdisk/work/mingjie2/sandbox/numba_dpex_825/numba-dpex/numba_dpex/examples/usm_ndarray.py", line 63, in <module>
    main()
  File "/localdisk/work/mingjie2/sandbox/numba_dpex_825/numba-dpex/numba_dpex/examples/usm_ndarray.py", line 57, in main
    driver(da, db, dc, global_size)
  File "/localdisk/work/mingjie2/sandbox/numba_dpex_825/numba-dpex/numba_dpex/examples/usm_ndarray.py", line 27, in driver
    data_parallel_sum[global_size, dpex.DEFAULT_LOCAL_SIZE](a, b, c)
  File "/localdisk/work/mingjie2/sandbox/numba_dpex_825/numba-dpex/numba_dpex/compiler.py", line 792, in __call__
    raise IndeterminateExecutionQueueError(
numba_dpex.utils.misc.IndeterminateExecutionQueueError: Data passed as argument are not equivalent. Please create dpctl.tensor.usm_ndarray with equivalent SYCL queue.
```

**Comment by mingjie-intel** [comment]
Fixed in PR #840.
