### ISSUE TITLE
Matrix multiplication kernel example is broken

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/numba-dpex#872]
Updating the `numba_dpex/examples/matmul.py` to use `dpctl.tensor.usm_ndarray` causes a type inference error. May be related to #871.

```

import dpctl
import dpctl.tensor as dpt
import numpy as np

import numba_dpex as dpex


@dpex.kernel
def gemm(a, b, c):
    """
    A basic DGEMM implemented as a ``kernel`` function.
    """
    i = dpex.get_global_id(0)
    j = dpex.get_global_id(1)
    if i >= c.shape[0] or j >= c.shape[1]:
        return
    c[i, j] = 0
    for k in range(c.shape[0]):
        c[i, j] += a[i, k] * b[k, j]


# Array dimensions
X = 1024
Y = 16
global_size = X, X

griddim = X, X
blockdim = Y, Y


def driver(a, b, c):
    # Invoke the kernel
    gemm[griddim, blockdim](a, b, c)


def main():
    a = np.arange(X * X, dtype=np.float32).reshape(X, X)
    b = np.array(np.random.random(X * X), dtype=np.float32).reshape(X, X)
    c = np.ones_like(a).reshape(X, X)

    device = dpctl.select_default_device()
    a_dpt = dpt.arange(X * X, dtype=dpt.float32, device=device)
    dpt.reshape(a_dpt, (X, X))
    b_dpt = dpt.asarray(b, dtype=dpt.float32, device=device)
    dpt.reshape(b_dpt, (X, X))
    c_dpt = dpt.ones_like(a_dpt)
    dpt.reshape(c_dpt, (X, X))

    print("Using device ...")
    device.print_device_info()

    driver(a_dpt, b_dpt, c_dpt)

    # Host compute using standard NumPy
    Amat = np.matrix(a)
    Bmat = np.matrix(b)
    Cans = Amat * Bmat

    # Check result
    assert np.allclose(c, Cans)

    print("Done...")


if __name__ == "__main__":
    main()

```

Backtrace

```

Traceback (most recent call last):
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/examples/matmul.py", line 72, in <module>
    main()
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/examples/matmul.py", line 58, in main
    driver(a_dpt, b_dpt, c_dpt)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/examples/matmul.py", line 39, in driver
    gemm[griddim, blockdim](a, b, c)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/core/kernel_interface/dispatcher.py", line 577, in __call__
    ) = self._compile_and_cache(
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/core/kernel_interface/dispatcher.py", line 152, in _compile_and_cache
    kernel.compile(
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/core/kernel_interface/spirv_kernel.py", line 123, in compile
    cres = compile_with_dpex(
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/localdisk/work/diptorup/devel/numba-dpex/numba_dpex/core/compiler.py", line 264, in compile_with_dpex
    cres = compiler.compile_extra(
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/localdisk/work/diptorup/.conda/envs/dpex-devel/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in dpex_nopython mode pipeline (step: nopython frontend)
tuple index out of range
During: typing of static-get-item at /localdisk/work/diptorup/devel/numba-dpex/numba_dpex/examples/matmul.py (21)

File "numba_dpex/examples/matmul.py", line 21:
def gemm(a, b, c):
    <source elided>
    j = dpex.get_global_id(1)
    if i >= c.shape[0] or j >= c.shape[1]:
```

**Comment by diptorupd** [comment]
Fixed. The issue was in the example and the reproducer. The output of the `reshape` was not assigned to the array variable. Refer the updated matmul.py.
